services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=quo_digital_db'
      - 'POSTGRES_USER=demo_user'
      - 'POSTGRES_PASSWORD=demo_pass'
